name: Some Repo That Runs CI
on: 
  push:
    branches:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  call-workflow:
    uses: CheeseInTheDark/a-new-test-repo/.github/workflows/main.yml@test-branch